// petfiesta-angular/src/app/pet-profile-update/pet-profile-update.component.ts
import {Component, OnInit} from '@angular/core';
import {FormsModule} from "@angular/forms";
import {NgFor} from "@angular/common";
import {MatSelectModule} from "@angular/material/select";
import {PetProfile} from "../entities/pet-profile";
import {Tag} from "../entities/tag";
import {PetProfileService} from "../services/pet-profile.service";
import {PassportService} from "../services/passport.service";
import {TagService} from "../services/tag.service";
import {CookieService} from "ngx-cookie-service";
import {ActivatedRoute, Router} from "@angular/router";
import {ModifyTag} from "../entities/modify-tag";

@Component({
  selector: 'app-pet-profile-update',
  standalone: true,
    imports: [FormsModule, NgFor, MatSelectModule],
  templateUrl: './pet-profile-update.component.html'
})

export class PetProfileUpdateComponent implements OnInit {
    petProfile: PetProfile = new PetProfile();
    petProfileId: number;
    tagsList: Tag[] = [];
    originalTags: Tag[] = [];
    private userId: string;
    private token: string;

    purposeList = [
        { value: 'WALKING', label: 'Walking' },
        { value: 'PROCREATION', label: 'Procreation' }
    ];
    kindList = [
        { value: 'DOG', label: 'Dog' },
        { value: 'CAT', label: 'Cat' },
        { value: 'OTHER', label: 'Other' }
    ];


    constructor(private petProfileService: PetProfileService,
                private passportService: PassportService,
                private tagService: TagService,
                private cookieService: CookieService,
                private activatedRoute: ActivatedRoute,
                private router: Router)
    {
        this.userId = cookieService.get('userId');
        this.token = cookieService.get('token');
        this.petProfileId = activatedRoute.snapshot.params["id"];
    }

    async ngOnInit(){
        this.petProfile = await this.petProfileService.getPetProfile(this.petProfileId);
        this.petProfile.userId = parseInt(this.userId);
        this.petProfile.passport = await this.passportService.getPassportByPetProfileId(this.petProfileId);
        this.petProfile.passport.petProfileId = this.petProfileId;
        this.petProfile.tags = await this.tagService.getTagsByPetProfileId(this.petProfileId);
        this.originalTags = this.petProfile.tags;
        this.tagsList = await this.tagService.getTags();
    }

    async updatePetProfile() {
        await this.petProfileService.updatePetProfile(this.petProfile, this.token);
        await this.passportService.updatePassport(this.petProfile.passport, this.token);

        let tags = this.petProfile.tags;
        const tagsToAdd: Tag[] = tags.filter(tag => !this.originalTags.some(originalTag => tag.id === originalTag.id));

        for (let tag of tagsToAdd) {
            await this.tagService.addTagToPetProfile(new ModifyTag(tag.id, this.petProfileId), this.token);
        }

        const tagsToDelete = this.originalTags.filter(originalTag => !tags.some(tag => tag.id === originalTag.id));

        for (let tag of tagsToDelete) {
            await this.tagService.deleteTagFromPetProfile(new ModifyTag(tag.id, this.petProfileId), this.token);
        }

        await this.router.navigate(["/pet-profiles"]);
    }

}

<section class="form-container main-content">
    <div class="form create-form">
        <h1>Update pet profile</h1>
        <input
            placeholder="Name"
            class="form-control input-margin"
            type="text"
            [(ngModel)]="petProfile.passport.name"
        />
        <input
            placeholder="Birth date"
            class="form-control input-margin"
            type="date"
            [(ngModel)]="petProfile.passport.birthDate"
        />
        <select class="input-margin form-control" [(ngModel)]="petProfile.passport.kind">
            <option value="" disabled selected>Kind</option>
            <option *ngFor="let kind of kindList" [ngValue]="kind.value">{{ kind.label }}</option>
        </select>
        <input
            placeholder="Breed"
            class="form-control input-margin"
            type="text"
            [(ngModel)]="petProfile.passport.breed"
        />
        <textarea
            placeholder="Bio"
            class="form-control input-margin"
            type="text"
            [(ngModel)]="petProfile.passport.bio"></textarea>

        <select class="form-control input-margin" [(ngModel)]="petProfile.purpose">
            <option value="" disabled selected>Purpose</option>
            <option *ngFor="let purpose of purposeList" [ngValue]="purpose.value">{{ purpose.label }}</option>
        </select>

        <select multiple class="form-control input-margin" [(ngModel)]="petProfile.tags">
            <option value="" disabled>Tags</option>
            <option *ngFor="let tag of tagsList" [ngValue]="tag">{{ tag.name }}</option>
        </select>


        <button class="btn btn-success" (click)="updatePetProfile()">Update</button>
    </div>
</section>

// petfiesta-react/src/routes/petProfileUpdate.js
import {useLoaderData, useNavigate} from "react-router-dom";
import React, {useContext, useEffect, useState} from "react";
import Select from "react-select";
import {updatePetProfile} from "../api/petProfileService";
import {AppContext} from "../contexts/contexts";
import {getPassportByPetProfileId, updatePassport} from "../api/passportService";
import {addTagToPetProfile, deleteTagFromPetProfile, getTags, getTagsByPetProfileId} from "../api/tagService";



export function PetProfileUpdate() {
    const appContext = useContext(AppContext);

    const navigate = useNavigate();

    const { petProfile } = useLoaderData();

    useEffect(() => {
        if (petProfile) {
            setPurpose(purposeList.find(item => item.value === petProfile.purpose))
            loadData()
        }
    }, [petProfile]);

    const [passportId, setPassportId] = useState();
    const [name, setName] = useState('')
    const [birthDate, setBirthDate] = useState('')
    const [kind, setKind] = useState({})
    const [breed, setBreed] = useState('')
    const [bio, setBio] = useState('')
    const [purpose, setPurpose] = useState({});
    const [tags, setTags] = useState([]);
    const [originalTags, setOriginalTags] = useState([]);

    const handleSelectKind = (selectedOption) => {
        setKind(selectedOption);
    };

    const handleSelectPurpose = (selectedOptions) => {
        setPurpose(selectedOptions);
    };

    const handleSelectTags = (selectedOptions) => {
        setTags(selectedOptions)
    }

    loadTags()

    let tagsList = []

    let purposeList = [
        {value: 'WALKING', label: 'Walking'},
        {value: 'PROCREATION', label: 'Procreation'}
    ]

    let kindList = [
        {value: 'DOG', label: 'Dog'},
        {value: 'CAT', label: 'Cat'},
        {value: 'OTHER', label: 'Other'},
    ]

    return (
        <section className="form-container main-content">
            <div className="form update-form">
                <h1>Update pet profile</h1>
                <input
                    placeholder="name"
                    className="form-control input-margin"
                    type="text"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                />
                <input
                    placeholder="birth date"
                    className="form-control input-margin"
                    type="date"
                    value={birthDate}
                    onChange={(e) => setBirthDate(e.target.value)}
                />
                <Select
                    className="input-margin"
                    options={kindList}
                    placeholder="kind"
                    value={kind}
                    isSearchable={true}
                    onChange={handleSelectKind}
                />
                <input
                    placeholder="breed"
                    className="form-control input-margin"
                    type="text"
                    value={breed}
                    onChange={(e) => setBreed(e.target.value)}
                />
                <textarea
                    placeholder="bio"
                    className="form-control input-margin"
                    type="text"
                    value={bio}
                    onChange={(e) => setBio(e.target.value)}
                />
                <Select
                    className="input-margin"
                    options={purposeList}
                    placeholder="purpose"
                    value={purpose}
                    isSearchable={true}
                    onChange={handleSelectPurpose}
                />

                <Select
                    className="input-margin"
                    options={tagsList}
                    placeholder="Tags"
                    value={tags}
                    onChange={handleSelectTags}
                    isSearchable={true}
                    isMulti
                />


                <button className="btn btn-primary" onClick={updatePetProfileClick}>
                    Update
                </button>
            </div>
        </section>
    );

    async function updatePetProfileClick() {
        const token = appContext.cookies.token

        petProfile.userId = appContext.cookies.userId
        petProfile.purpose = purpose.value
        await updatePetProfile(petProfile, token)

        let passport = {
            petProfileId: petProfile.id,
            id: passportId,
            name: name,
            birthDate: birthDate,
            kind: kind.value,
            breed: breed,
            bio: bio
        };
        await updatePassport(passport, token)

        const tagsToAdd = tags.filter(tag => !originalTags.some(originalTag => tag.value === originalTag.value))

        for (const tag of tagsToAdd) {
            await addTagToPetProfile({ tagId: tag.value, petProfileId: petProfile.id }, token);
        }

        const tagsToDelete = originalTags.filter(originalTag => !tags.some(tag => tag.value === originalTag.value))

        for (const tag of tagsToDelete) {
            await deleteTagFromPetProfile({ tagId: tag.value, petProfileId: petProfile.id }, token);
        }

        navigate('/pet-profiles')
    }

    async function loadData() {
        const passport = await getPassportByPetProfileId(petProfile.id)
        setPassportId(passport.id)
        setName(passport.name)
        setBirthDate(passport.birthDate.substring(0, 10))
        setKind(kindList.find(item => item.value === passport.kind))
        setBreed(passport.breed)
        setBio(passport.bio)

        const tags = await getTagsByPetProfileId(petProfile.id)
        const normalizedTags = []
        tags.map(tag => normalizedTags.push({value: tag.id, label: tag.name}))
        setTags(normalizedTags)
        setOriginalTags(normalizedTags)
    }

    async function loadTags() {
        const tags = await getTags();
        tags.map(tag => tagsList.push({value: tag.id, label: tag.name}))
    }
}
