// petfiesta-angular/src/app/pet-profile-create/pet-profile-create.component.ts
import {Component, OnInit} from '@angular/core';
import {FormsModule} from "@angular/forms";
import {NgFor} from "@angular/common";
import {PetProfile} from "../entities/pet-profile";
import {PetProfileService} from "../services/pet-profile.service";
import {TagService} from "../services/tag.service";
import {CookieService} from "ngx-cookie-service";
import {PassportService} from "../services/passport.service";
import {ModifyTag} from "../entities/modify-tag";
import {Router} from "@angular/router";
import {Tag} from "../entities/tag";
import {MatSelectModule} from '@angular/material/select';


@Component({
  selector: 'app-pet-profile-create',
  standalone: true,
  imports: [FormsModule, NgFor, MatSelectModule],
  templateUrl: './pet-profile-create.component.html'
})

export class PetProfileCreateComponent implements OnInit {
    petProfile: PetProfile = new PetProfile();
    tagsList: Tag[] = [];
    private userId: string;
    private token: string;

    purposeList = [
        { value: 'WALKING', label: 'Walking' },
        { value: 'PROCREATION', label: 'Procreation' }
    ];
    kindList = [
        { value: 'DOG', label: 'Dog' },
        { value: 'CAT', label: 'Cat' },
        { value: 'OTHER', label: 'Other' }
    ];


    constructor(private petProfileService: PetProfileService,
                private passportService: PassportService,
                private tagService: TagService,
                private cookieService: CookieService,
                private router: Router)
    {
        this.userId = cookieService.get('userId');
        this.token = cookieService.get('token');
        this.petProfile.userId = parseInt(this.userId);
    }

    async ngOnInit(){
        this.tagsList = await this.tagService.getTags();
    }

    async createPetProfile() {
        const newPetProfile = await this.petProfileService.createPetProfile(this.petProfile, this.token);

        this.petProfile.passport.petProfileId = newPetProfile.id;

        await this.passportService.createPassport(this.petProfile.passport, this.token);

        for (let tag of this.petProfile.tags) {
            console.log(tag);
            await this.tagService.addTagToPetProfile(new ModifyTag(tag.id, newPetProfile.id), this.token)
        }

        await this.router.navigate(["/pet-profiles"]);
    }
}

<section class="form-container main-content">
    <div class="form create-form">
        <h1>Create pet profile</h1>
        <input
            placeholder="Name"
            class="form-control input-margin"
            type="text"
            [(ngModel)]="petProfile.passport.name"
        />
        <input
            placeholder="Birth date"
            class="form-control input-margin"
            type="date"
            [(ngModel)]="petProfile.passport.birthDate"
        />
        <select class="input-margin form-control" [(ngModel)]="petProfile.passport.kind">
            <option value="" disabled selected>Kind</option>
            <option *ngFor="let kind of kindList" [ngValue]="kind.value">{{ kind.label }}</option>
        </select>
        <input
            placeholder="Breed"
            class="form-control input-margin"
            type="text"
            [(ngModel)]="petProfile.passport.breed"
        />
        <textarea
            placeholder="Bio"
            class="form-control input-margin"
            type="text"
            [(ngModel)]="petProfile.passport.bio"></textarea>

        <select class="form-control input-margin" [(ngModel)]="petProfile.purpose">
            <option value="" disabled selected>Purpose</option>
            <option *ngFor="let purpose of purposeList" [ngValue]="purpose.value">{{ purpose.label }}</option>
        </select>

        <select multiple class="form-control input-margin" [(ngModel)]="petProfile.tags">
            <option value="" disabled>Tags</option>
            <option *ngFor="let tag of tagsList" [ngValue]="tag">{{ tag.name }}</option>
        </select>


        <button class="btn btn-success" (click)="createPetProfile()">Create</button>
        </div>
        </section>

// petfiesta-react/src/routes/petProfileCreate.js
import React, {useContext, useState} from "react";
import {AppContext} from "../contexts/contexts";
import {useNavigate} from "react-router-dom";
import Select from "react-select";
import {createPetProfile} from "../api/petProfileService";
import {createPassport} from "../api/passportService";
import {addTagToPetProfile, getTags} from "../api/tagService";



export function PetProfileCreate() {
    const appContext = useContext(AppContext);

    const navigate = useNavigate();

    const [name, setName] = useState('')
    const [birthDate, setBirthDate] = useState('')
    const [kind, setKind] = useState('')
    const [breed, setBreed] = useState('')
    const [bio, setBio] = useState('')
    const [purpose, setPurpose] = useState('');
    const [tags, setTags] = useState([]);

    let tagsList = []

    loadTags()

    let purposeList = [
        {value: 'WALKING', label: 'Walking'},
        {value: 'PROCREATION', label: 'Procreation'}
    ]
    let kindList = [
        {value: 'DOG', label: 'Dog'},
        {value: 'CAT', label: 'Cat'},
        {value: 'OTHER', label: 'Other'},
    ]

    const handleSelectPurpose = (selectedOption) => {
        setPurpose(selectedOption);
    };

    const handleSelectKind = (selectedOption) => {
        setKind(selectedOption);
    };

    const handleSelectTags = (selectedOptions) => {
        setTags(selectedOptions)
    }

    return (
        <section className="form-container main-content">
            <div className="form create-form">
                <h1>Create pet profile</h1>
                <input
                    placeholder="name"
                    className="form-control input-margin"
                    type="text"
                    onChange={(e) => setName(e.target.value)}
                />
                <input
                    placeholder="birth date"
                    className="form-control input-margin"
                    type="date"
                    onChange={(e) => setBirthDate(e.target.value)}
                />
                <Select
                    className="input-margin"
                    options={kindList}
                    placeholder="kind"
                    value={kind}
                    isSearchable={true}
                    onChange={handleSelectKind}
                />
                <input
                    placeholder="breed"
                    className="form-control input-margin"
                    type="text"
                    onChange={(e) => setBreed(e.target.value)}
                />
                <textarea
                    placeholder="bio"
                    className="form-control input-margin"
                    type="text"
                    onChange={(e) => setBio(e.target.value)}
                />
                <Select
                    className="input-margin"
                    options={purposeList}
                    placeholder="purpose"
                    value={purpose}
                    isSearchable={true}
                    onChange={handleSelectPurpose}
                />

                <Select
                    className="input-margin"
                    options={tagsList}
                    placeholder="Tags"
                    value={tags}
                    onChange={handleSelectTags}
                    isSearchable={true}
                    isMulti
                />

                <button className="btn btn-success" onClick={createPetProfileClick}>Create</button>
            </div>
        </section>
    );

    async function createPetProfileClick() {
        const token = appContext.cookies.token

        let petProfile = {}
        petProfile.userId = appContext.cookies.userId
        petProfile.purpose = purpose.value
        petProfile = await createPetProfile(petProfile, token)

        let passport = {
            petProfileId: petProfile.id,
            name: name,
            birthDate: birthDate,
            kind: kind.value,
            breed: breed,
            bio: bio
        }
        await createPassport(passport, token)

        for (const tag of tags) {
            await addTagToPetProfile({ tagId: tag.value, petProfileId: petProfile.id }, token);
        }

        navigate('/pet-profiles')
    }

    async function loadTags() {
        const tags = await getTags();
        tags.map(tag => tagsList.push({value: tag.id, label: tag.name}))
    }
}
