// petfiesta-angular/src/app/tags/tags.component.ts
import { Component } from '@angular/core';
import {RouterLink} from "@angular/router";
import {NgFor} from "@angular/common";
import {Tag} from "../entities/tag";
import {TagService} from "../services/tag.service";

@Component({
  selector: 'app-tags',
  standalone: true,
  imports: [RouterLink, NgFor],
  templateUrl: './tags.component.html',
})
export class TagsComponent {
    tags: Tag[] = [];

    constructor(private tagService: TagService) {}

    async ngOnInit() {
        this.tags = await this.tagService.getTags();
    }

    async deleteTag(id: number) {
        await this.tagService.deleteTag(id);
        await this.ngOnInit();
    }
}

<section class="container ">
    <h1 class="h1">Tags</h1>
    <a routerLink="create/" class="btn btn-success">Create</a>
    <table class="table table-striped table-hover">
        <caption>...</caption>
        <thead class="">
        <tr class="">
            <th>
                Name
            </th>
        </tr>
        </thead>
        <tbody class="">
        <tr *ngFor="let tag of tags">
            <td>
                {{tag.name}}
            </td>
            <td>
                <a [routerLink]="['update/', tag.id]" class="btn btn-outline-primary">Update</a>
            </td>
            <td>
                <button
                    (click) = "deleteTag(tag.id)"
                    class="btn btn-danger">
                    Remove
                </button>
            </td>
        </tr>
        </tbody>
    </table>

</section>

// petfiesta-react/src/routes/tags.js
import React, { useState, useEffect } from 'react';
import { getTag, getTags, deleteTag} from "../api/tagService"
import { Link } from "react-router-dom";

export async function loader({ params }) {
    const tag = await getTag(params.tagId);
    return { tag };
}

export default function Tags() {
    const [Tags, setTags] = useState([]);
    const [reload, setReload] = useState(false);

    useEffect(() => {
        loadTags();
    }, [reload]);

    return (
        <section className="main-content">
            <div className="table-title tags-table">
                <h2>Tags</h2>
                <Link to="create/" className="btn btn-success">Create</Link>
                <table className="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Name</th>
                        </tr>
                    </thead>
                    <tbody>
                        {Tags.map(tag =>
                            <tr key={tag.id}>
                                <td>{tag.name}</td>
                                <td>
                                    <Link to={`update/${tag.id}`} className="btn btn-outline-primary">Update</Link>
                                </td>
                                <td>
                                    <button 
                                        onClick={() => removeTag(tag.id)} 
                                        value={tag.id}
                                        className="btn btn-outline-danger">
                                            Remove
                                    </button>
                                </td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </section>
    );

    async function loadTags() {
        const Tags = await getTags()
        setTags(Tags)
    }

    async function removeTag(id) {
        await deleteTag(id)
        setReload(!reload)
    }
}
