// petfiesta-react/src/components/navbar.js
import { Link } from "react-router-dom";

export default function Navbar() {
    return (
        <nav>
            <ul>
                <li>
                    <Link to={`/signin`}>sign in</Link>
                </li>
                <li>
                    <Link to={`/signup`}>sign up</Link>
                </li>
                <li>
                    <Link to={`/pet-profiles`}>Pet profiles</Link>
                </li>
                <li>
                    <Link to={`/tags`}>Tags </Link>
                </li>
            </ul>
        </nav>
    );
}

// petfiesta-angular/src/app/navbar/navbar.component.ts
import {Component, Input} from '@angular/core';
import { NgIf } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [NgIf, RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  @Input() isAuthenticated = false;
}

<header class="navigation-header">
  <nav class="navigation-menu">
    <ul>
      @if (isAuthenticated) {
        <li>
          <a class="menu-item" routerLink="/pet-profiles" routerLinkActive="active">Pet profiles</a>
        </li>
        <li>
          <a class="menu-item" routerLink="/tags" routerLinkActive="active">Tags</a>
        </li>
      }
      @else {
        <li>
          <a class="menu-item" routerLink="/signup" routerLinkActive="active">Sign up</a>
        </li>
        <li>
          <a class="menu-item" routerLink="/signin" routerLinkActive="active">Sign In</a>
        </li>
      }
    </ul>
  </nav>
</header>
