// petfiesta-react/src/routes/tagCreate.js
import {useNavigate} from "react-router-dom";
import React, {useState} from "react";
import {createTag} from "../api/tagService";

export function TagCreate() {
    const navigate = useNavigate();

    const [name, setName] = useState('');

    return (
        <section className="form-container main-content">
            <div className="form create-form">
                <h1>Create tag</h1>
                <input
                    placeholder="Name"
                    className="form-control input-margin"
                    type="text"
                    onChange={(e) => setName(e.target.value)}
                />
                <button className="btn btn-success" onClick={addTagClick}>Create</button>
            </div>
        </section>
    );

    async function addTagClick() {
        let tag = {}
        tag.name = name
        await createTag(tag)
        navigate('/tags')
    }
}

// petfiesta-angular/src/app/tag-create/tag-create.component.ts
import { Component } from '@angular/core';
import {FormsModule} from "@angular/forms";
import {NgFor} from "@angular/common";
import {Tag} from "../entities/tag";
import {TagService} from "../services/tag.service";
import {Router} from "@angular/router";

@Component({
  selector: 'app-tag-create',
  standalone: true,
  imports: [FormsModule, NgFor],
  templateUrl: './tag-create.component.html'
})

export class TagCreateComponent {
    tag: Tag = new Tag();

    constructor(private tagService: TagService, private router: Router) {}

    async createTag() {
        await this.tagService.createTag(this.tag);
        await this.router.navigate(["/tags"]);
    }
}

<section class="form-container main-content">
    <div class="form create-form">
        <h1>Create tag</h1>
        <input
            placeholder="Name"
            class="form-control input-margin"
            type="text"
            [(ngModel)]="tag.name"
        />
        <button class="btn btn-success" (click)="createTag()">Create</button>
    </div>
</section>
