// petfiesta-react/src/routes/tagUpdate.js
import {useLoaderData, useNavigate} from "react-router-dom";
import React, {useState} from "react";
import {updateTag} from "../api/tagService";

export function TagUpdate() {
    const navigate = useNavigate();

    const { tag } = useLoaderData();
    const [name, setName] = useState('');

    return (
        <section className="form-container main-content">
            <div className="form update-form">
                <h1>Update tag</h1>
                <input
                    placeholder="Name"
                    className="form-control input-margin"
                    type="text"
                    onChange={(e) => setName(e.target.value)}
                />
                <button className="btn btn-primary" onClick={updateTagClick}>
                    Update
                </button>
            </div>
        </section>
    );

    async function updateTagClick() {
        tag.name = name
        await updateTag(tag.id, tag)
        navigate('/tags')
    }
}

// petfiesta-angular/src/app/tag-update/tag-update.component.ts
import { Component } from '@angular/core';
import {FormsModule} from "@angular/forms";
import {NgFor} from "@angular/common";
import {Tag} from "../entities/tag";
import {TagService} from "../services/tag.service";
import {ActivatedRoute, Router} from "@angular/router";

@Component({
  selector: 'app-tag-update',
  standalone: true,
  imports: [FormsModule, NgFor],
  templateUrl: './tag-update.component.html',
  styleUrl: './tag-update.component.css'
})

export class TagUpdateComponent {
    tag: Tag = new Tag();
    id: number;

    constructor(private tagService: TagService,
                private router: Router,
                private activatedRoute: ActivatedRoute)
    {
        this.id = activatedRoute.snapshot.params["id"];
    }

    async ngOnInit() {
        this.tag = await this.tagService.getTag(this.id);
    }

    async updateTag() {
        await this.tagService.updateTag(this.id, this.tag);
        await this.router.navigate(["/tags"]);
    }
}

<section class="form-container main-content">
    <div class="form update-form">
        <h1>Update tag</h1>
        <input
            placeholder="Name"
            class="form-control input-margin"
            type="text"
            [(ngModel)]="tag.name"
        />
        <button class="btn btn-primary" (click)="updateTag()">
            Update
        </button>
    </div>
</section>
